apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo-nginx
spec:
  selector:
    app: nginx
    target: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-http
  type: LoadBalancer
