apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: application-policy
  namespace: application
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          env: application
    - ipBlock:
        cidr: 10.0.0.0/14 # the Pod range of the cluster
    - ipBlock:
        cidr: 35.191.0.0/16 # Google HealthCheck CIDR
    - ipBlock:
        cidr: 130.211.0.0/22 # Google HealthCheck CIDR
  podSelector: {}
  policyTypes:
  - Ingress