apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    tier: backend
    app: microservices-ci
  type: ClusterIP
  ports:
  - name: be
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    tier: backend
    app: microservices-ci
spec:
  selector:
    matchLabels:
      tier: backend
      app: microservices-ci
  template:
    metadata:
      labels:
        tier: backend
        app: microservices-ci
    spec:
      containers:
      - name: backend
        image: eu.gcr.io/<PROJECT_ID>/ms-ci-backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            cpu: "200m"
            memory: "200M"
        livenessProbe:
          httpGet:
            path: /hc
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /hc
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10 
        ports:
        - containerPort:  8080
          name: be
        env:
        - name: KZ_ENV
          value: "my CI app"