apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application/backend.yaml
- application/frontend.yaml
- application/ingress.yaml
- application/metadata.yaml
- application/namespaces.yaml
- application/proxy.yaml

- masquerading/masq.yaml # edit IPs before applying

- policies/policy.yaml # edit IPs before applying
