steps:

- name: gcr.io/cloud-builders/docker
  args:
  - "build"
  - "--tag=eu.gcr.io/$PROJECT_ID/env-node-site:latest"
  - "--tag=eu.gcr.io/$PROJECT_ID/env-node-site:$TAG_NAME"
  - "."

- name: gcr.io/cloud-builders/kubectl
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  args:
  - set
  - image
  - 'deployment/$_DEPLOYMENT_NAME'
  - 'webapp=eu.gcr.io/$PROJECT_ID/env-node-site:$TAG_NAME'

images:
- "eu.gcr.io/$PROJECT_ID/env-node-site:latest"