steps:

# Compile and package
- name: 'gcr.io/cloud-builders/mvn'
  args:
  - clean
  - package

# Build image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=eu.gcr.io/injenia-gcp-demo/esselunga-test:$BRANCH_NAME'
  - '--tag=eu.gcr.io/injenia-gcp-demo/esselunga-test:$SHORT_SHA'
  - '--tag=eu.gcr.io/injenia-gcp-demo/esselunga-test:latest'
  - '.'

# Push the image, it will be used in the next step
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "eu.gcr.io/injenia-gcp-demo/esselunga-test:latest"]

# # Deploy
# - name: 'gcr.io/cloud-builders/kubectl'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=intesa-cluster2'
#   args:
#   - set
#   - image
#   - 'deployment/esselunga-test'
#   - 'tomcat=eu.gcr.io/injenia-esa/esselunga-test:$SHORT_SHA'
#   - '--namespace=$BRANCH_NAME'

images:
- 'eu.gcr.io/injenia-gcp-demo/esselunga-test:$BRANCH_NAME'
- 'eu.gcr.io/injenia-gcp-demo/esselunga-test:$SHORT_SHA'