apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: demo-volumes
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi
  storageClassName: slow