apiVersion: v1
kind: Service
metadata:
  name: pv-service
  namespace: demo-volumes
spec:
  selector:
    app: pv
    target: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: volumes-http
  type: LoadBalancer
