apiVersion: apps/v1 
kind: Deployment
metadata:
  name: env-deployment
  labels:
    app: env-site
    target: demo
spec:
  selector:
    matchLabels:
      app: env-site
      target: demo
  replicas: 1 
  template:
    metadata:
      labels:
        app: env-site
        target: demo
    spec:
      containers:
      - name: webapp
        image: eu.gcr.io/fausto-lab/env-node-site:v1
        ports:
        - containerPort: 8080
        env:
        - name: KZ_ENV
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: kzEnv
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m"
          requests:
            memory: "100Mi"
            cpu: "100m"
